{% set name = "skater" %}
{% set version = "1.1.0" %}
{% set sha256 = "19f96f09d6134e189088ee63c3a839f34f67a808521f737e3dc34647b99850d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - scipy >=0.15
    - numpy >=1.10
    - scikit-learn >=0.18
    - pandas >=0.22
    - matplotlib
    - pathos
    - dill >=0.2.6
    - requests
    - ds-lime >=0.1.1.21
    - scikit-image >=0.14,<0.15
    - joblib
    - rpy2 ==2.9.1  # [py3k]
    - jinja2
    - beautifulsoup4

test:
  imports:
    - skater
    - skater.model
    - skater.data
    - skater.core.explanations
    - skater.util
    - skater.core.local_interpretation.lime.lime_tabular
    - skater.util.dataops
    - skater.core.global_interpretation.partial_dependence

about:
  home: https://github.com/datascienceinc/Skater
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python Library for Model Agnostic Interpretation'
  description: |
    Skater is a python package for model agnostic interpretation of predictive
    models. With Skater, you can unpack the internal mechanics of arbitrary
    models; as long as you can obtain inputs, and use a function to obtain
    outputs, you can use Skater to learn about the models internal
    decision policies.
  doc_url: https://datascienceinc.github.io/Skater/index.html
  dev_url: https://github.com/datascienceinc/Skater

extra:
  recipe-maintainers:
    - benvandyke
    - aikramer2
