travis:
  secure:
    BINSTAR_TOKEN: Ou/zfqknbh9Gt0H98PCQ0aOdycHRWa6/7zBT6Fa5dI/KLID+ScKfsjKttVx3rXBKs0vorTXTvoSzAEJk+IQOa9mVeiqwHlckW2g/G3an/67vPpsytiv/eEYkBuUhOeAWnrS8x2eCtaDfhzF1V28RpwJypnO/QHyrzZcQ33mItkuGcwqw4I4Ct4Hy9hKdtCk93Ug36p/UKmGgEnxWRsPDnTR7xAyy+LYPP0hDQQNo68vCBDe2WQubp84+rX2Z1wA8Fg+XxrbGbsuG6YvLlM2VKEsuqqpgL5h0rtjPWZiKqPxsVE4YFiPiJruF753KsG8Gb0ZIFCNQFmxuLdzNNptN9xO0pBddz1Ggnh2IIZKU2N5Hb/1QVRTZzzLFdvLlfroJplscPTKzHCBwr5zujiNgAfclUQvtfTOnBPx/reUcUmMzTzmiKP1vljl66N1pzxJ9EgRjIsU1WO34Pz4JDMiyTwnN0hpmXIefffOL6Erh+PB54JBp5F0DYWrOjKg3H7OoOce8TJu4kDhxMmMn5psq1KFJIY1xU4O63DaNziqQmLKmhNfyh9wtEJQgOaIuNPjHdw8lKkqvv9g3D5AcfHzXqQx6oiwGDK/FuY12JRowN2PKo68W+iRB4lq0pxSDzKQMiqxB2ghxN7iIGhFpFPKFxXp0GGJRSI6pUuaHy/3gWew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
