appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LCYW4imkjHjZ/DGckG89UcITKs4MtoQNhqhz7udZUgR902cHOQUXRtOAKy9RrPUOgQ/ewZjikxKTsCgTCdWgYK6n/TlAHLYelpwwwKXASiZDf04GqnWG9CMooeR0GmCWy/7QLWZA3fEfueQsG2tystqz9EpBnGFffTBVvpEk8ZgXjojBKodg2PTfWX4tyMW3eL9blltH4fG6MoHM4ov+eE2WcIHXvKj8IBt6QAADuISkPffX6GCfUwBzAN+/rS6+FoTUX15QpmlBbqcYucgWvjzkhM8mI2RdFrXW7hkL+mB2PQz4cU6sPwx1GSGZ4JNfiJ3LPzGFRG6mvMSIzFxkH5YSyluiLfyXjsHoFtUiShPt1qiB65W1cOQqjHLaYHSxyPFulH3Jqkjlt/uxatE1FV4MmLll0a8dehL3v/12Aq4sgs1vJHW/KKAwaxZ7rXnVfmWowg+3Sr46Sxs+H0dxSbuiCE0YHrWHElQ90yBPqqjEsS5XqKxTOE79tpUggfKIK380SZ2Yfg9kYqrXm9bXgRN1kYm5bqIV9zlpzeGZQJsZE9BNBYyOvG3SUgzg2StORnkMEpiFQrpL2bJBGxwzdZyH0HZVCJizI4T6i8IT0gC8xqzKxGUwJ44lYT6P907NgDWcv40uHVZvDEhngfS00hmWr1H0RI0CEDMO/c5H+I0=}
conda_forge_output_validation: true
